[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "bun", "mysql80"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "bun install"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
